==>(quote 3)
==>(quote "hi")
==>(quote a)
==>(quote (+ 3 4))
==>(quote (define x 25))
==>(quote (lambda (x) (+ x 3)))
==>(quote 3)
==>(quote "hi")
==>(quote a)
==>(quote (+ 3 4))
==>(quote (define x 25))
==>(quote (lambda (x) (+ x 3)))
